//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JWTPlay2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Size
    {
        public int product_id { get; set; }
        public int product_size1 { get; set; }
        public Nullable<double> price { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Size Size { get; set; }
    }
}
